/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move money between two accounts
         * @description Expands to an ordinary two-line entry and runs through the identical validation.
         */
        post: operations["transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List statement imports */
        get: operations["list"];
        put?: never;
        /** Import a bank statement and reconcile it */
        post: operations["importStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{id}/breaks/{breakId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a break by posting an adjusting entry */
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{id}/breaks/{breakId}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record why a break exists
         * @description Moves no money. Correct for a timing difference.
         */
        post: operations["explain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the journal, most recent first
         * @description Cursor-paginated. Offset pagination over an append-only ledger repeats or skips rows as entries arrive mid-read, so it is not offered.
         */
        get: operations["list_1"];
        put?: never;
        /**
         * Post a journal entry
         * @description Requires an Idempotency-Key; safe to retry.
         */
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries/{id}/reversal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse an entry
         * @description The server derives the mirrored lines from the original; the body cannot supply them.
         */
        post: operations["reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Presenting an already-rotated token revokes the whole family.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session's refresh token family */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for an access token
         * @description The refresh token is returned as an HttpOnly cookie, not in the body.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trial balance as of a date
         * @description outOfBalanceMinor is always computed and always returned.
         */
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The reconciliation bridge
         * @description difference equals bridgeTotalMinor, or bridgeBalanced is false and the engine has a bug.
         */
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{id}/breaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Typed breaks for one import */
        get: operations["breaks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one entry */
        get: operations["byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated caller and what they may do */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the chart of accounts */
        get: operations["all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one account */
        get: operations["byId_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Balance as of a date
         * @description Derived from the journal at read time; nothing is cached. See ADR-0003.
         */
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JSON Web Key Set for verifying access tokens */
        get: operations["jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TransferRequest: {
            /** Format: date */
            effectiveDate: string;
            fromAccountCode: string;
            toAccountCode: string;
            /** Format: int64 */
            amountMinor?: number;
            currency: string;
            description: string;
            externalRef?: string;
        };
        EntryLineResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            lineNo?: number;
            /** Format: uuid */
            accountId?: string;
            accountCode?: string;
            accountName?: string;
            direction?: string;
            amount?: components["schemas"]["MoneyResponse"];
            memo?: string;
        };
        EntryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            sequenceNo?: number;
            /** Format: date */
            effectiveDate?: string;
            /** Format: date-time */
            postedAt?: string;
            description?: string;
            currency?: string;
            source?: string;
            externalRef?: string;
            /** Format: uuid */
            reversalOfEntryId?: string;
            reversalReason?: string;
            totalDebit?: components["schemas"]["MoneyResponse"];
            totalCredit?: components["schemas"]["MoneyResponse"];
            lines?: components["schemas"]["EntryLineResponse"][];
            /** Format: uuid */
            createdBy?: string;
            requestId?: string;
        };
        MoneyResponse: {
            /** Format: int64 */
            amountMinor?: number;
            currency?: string;
            amount?: string;
        };
        BridgeRow: {
            /** Format: uuid */
            breakId?: string;
            /** @enum {string} */
            type?: "MISSING_IN_LEDGER" | "MISSING_IN_STATEMENT" | "AMOUNT_MISMATCH" | "TIMING_DIFFERENCE" | "DUPLICATE_IN_LEDGER" | "DUPLICATE_IN_STATEMENT" | "CURRENCY_MISMATCH" | "OPENING_BALANCE_MISMATCH";
            /** @enum {string} */
            status?: "OPEN" | "EXPLAINED" | "RESOLVED" | "WRITTEN_OFF";
            /** Format: int64 */
            deltaMinor?: number;
            detail?: string;
            data?: {
                [key: string]: unknown;
            };
        };
        ReconciliationReport: {
            /** Format: uuid */
            importId?: string;
            accountCode?: string;
            accountName?: string;
            /** Format: date */
            periodStart?: string;
            /** Format: date */
            periodEnd?: string;
            currency?: string;
            /** Format: int64 */
            ledgerClosingMinor?: number;
            /** Format: int64 */
            statementClosingMinor?: number;
            /** Format: int64 */
            differenceMinor?: number;
            /** Format: int32 */
            matchedCount?: number;
            /** Format: int64 */
            matchedAmountMinor?: number;
            /** Format: int32 */
            unmatchedStatementLines?: number;
            /** Format: int32 */
            unmatchedJournalLines?: number;
            bridge?: components["schemas"]["BridgeRow"][];
            /** Format: int64 */
            bridgeTotalMinor?: number;
            bridgeBalanced?: boolean;
            /** Format: double */
            matchRate?: number;
            /** Format: date-time */
            generatedAt?: string;
        };
        ResolveRequest: {
            counterAccountCode: string;
            explanation: string;
            /** Format: date */
            effectiveDate?: string;
            writeOff?: boolean;
        };
        ResolveResponse: {
            /** Format: uuid */
            breakId: string;
            /** Format: uuid */
            adjustingEntryId: string;
        };
        ExplainRequest: {
            explanation: string;
        };
        Line: {
            accountCode: string;
            direction: string;
            /** Format: int64 */
            amountMinor?: number;
            memo?: string;
        };
        PostEntryRequest: {
            /** Format: date */
            effectiveDate: string;
            description: string;
            currency: string;
            externalRef?: string;
            lines: components["schemas"]["Line"][];
        };
        ReversalRequest: {
            /** Format: date */
            effectiveDate?: string;
            reason: string;
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            /** Format: date-time */
            expiresAt?: string;
            email?: string;
            displayName?: string;
            role?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        Row: {
            accountCode?: string;
            accountName?: string;
            type?: string;
            debit?: components["schemas"]["MoneyResponse"];
            credit?: components["schemas"]["MoneyResponse"];
            balance?: components["schemas"]["MoneyResponse"];
        };
        TrialBalanceResponse: {
            /** Format: date */
            asOf?: string;
            currency?: string;
            rows?: components["schemas"]["Row"][];
            totalDebit?: components["schemas"]["MoneyResponse"];
            totalCredit?: components["schemas"]["MoneyResponse"];
            /** Format: int64 */
            outOfBalanceMinor?: number;
            balanced?: boolean;
        };
        StatementImport: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            accountId?: string;
            accountCode?: string;
            currency?: string;
            /** Format: date */
            periodStart?: string;
            /** Format: date */
            periodEnd?: string;
            /** Format: int64 */
            openingBalanceMinor?: number;
            /** Format: int64 */
            closingBalanceMinor?: number;
            sourceFilename?: string;
            /** @enum {string} */
            status?: "PENDING" | "MATCHING" | "COMPLETED" | "FAILED";
            /** Format: date-time */
            importedAt?: string;
            /** Format: uuid */
            importedBy?: string;
            failureReason?: string;
        };
        ReconciliationBreak: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            importId?: string;
            /** @enum {string} */
            type?: "MISSING_IN_LEDGER" | "MISSING_IN_STATEMENT" | "AMOUNT_MISMATCH" | "TIMING_DIFFERENCE" | "DUPLICATE_IN_LEDGER" | "DUPLICATE_IN_STATEMENT" | "CURRENCY_MISMATCH" | "OPENING_BALANCE_MISMATCH";
            /** @enum {string} */
            status?: "OPEN" | "EXPLAINED" | "RESOLVED" | "WRITTEN_OFF";
            /** Format: uuid */
            statementLineId?: string;
            /** Format: uuid */
            journalLineId?: string;
            /** Format: int64 */
            deltaMinor?: number;
            currency?: string;
            detail?: {
                [key: string]: unknown;
            };
            explanation?: string;
            /** Format: uuid */
            resolvingEntryId?: string;
            /** Format: uuid */
            resolvedBy?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        PageResponseEntryResponse: {
            items?: components["schemas"]["EntryResponse"][];
            nextCursor?: string;
            hasMore?: boolean;
        };
        MeResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
            role?: string;
            can?: string[];
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            type?: string;
            currency?: string;
            status?: string;
            /** Format: uuid */
            parentId?: string;
        };
        BalanceResponse: {
            /** Format: uuid */
            accountId?: string;
            code?: string;
            /** Format: date */
            asOf?: string;
            balance?: components["schemas"]["MoneyResponse"];
            signedBalance?: components["schemas"]["MoneyResponse"];
            totalDebit?: components["schemas"]["MoneyResponse"];
            totalCredit?: components["schemas"]["MoneyResponse"];
            /** Format: int64 */
            lineCount?: number;
            /** Format: date-time */
            derivedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    transfer: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                accountId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatementImport"][];
                };
            };
        };
    };
    importStatement: {
        parameters: {
            query: {
                accountCode: string;
                periodStart: string;
                periodEnd: string;
                openingBalanceMinor: number;
                closingBalanceMinor: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationReport"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
                breakId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResolveResponse"];
                };
            };
        };
    };
    explain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                breakId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                accountId?: string;
                source?: "API" | "TRANSFER" | "REVERSAL" | "IMPORT" | "ADJUSTMENT" | "SEED";
                externalRef?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseEntryResponse"];
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostEntryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryResponse"];
                };
            };
        };
    };
    reverse: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ledger_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ledger_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    trialBalance: {
        parameters: {
            query?: {
                asOf?: string;
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrialBalanceResponse"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationReport"];
                };
            };
        };
    };
    breaks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationBreak"][];
                };
            };
        };
    };
    byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    byId_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
    jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
}
